In [5]:
print("hello")
import calc
calc.add(10,20)

hello

30

In [3]:
def multiphy(a,b):
    return a * b
    return result
def divide(a,b):
    return a / b
    return result
def subtract(a,b):
    return a - b
    return result

from calc import multiply
print(multiply(2,3))

6

In [5]:
import math
import random
import datetime
import os
import sys
import time

print("### 파이썬 내장 모듈 예시 실행 ###\n")

# 1. math: 수학 함수
print("1. math 모듈")
math_result = math.sqrt(16)
print(f"math.sqrt(16) 실행 결과: {math_result}\n")

# 2. random: 랜덤값 생성
print("2. random 모듈")
random_result = random.randint(1, 10)
print(f"random.randint(1, 10) 실행 결과: {random_result} (1~10 사이의 무작위 정수)\n")

# 3. datetime: 날짜와 시간 처리
print("3. datetime 모듈")
datetime_result = datetime.datetime.now()
print(f"datetime.datetime.now() 실행 결과: {datetime_result}\n")

# 4. os: 운영체제 관련 기능
print("4. os 모듈")
os_result = os.getcwd()
print(f"os.getcwd() 실행 결과: {os_result} (현재 작업 중인 디렉토리 경로)\n")

# 5. sys: 시스템 관련 정보
print("5. sys 모듈")
sys_result = sys.version
print(f"sys.version 실행 결과:\n{sys_result}\n")

# 6. time: 시간 관련 기능
print("6. time 모듈")
print("time.sleep(1) 실행... (1초간 대기합니다)")
time.sleep(1)
print("1초 대기 완료!")

### 파이썬 내장 모듈 예시 실행 ###

1. math 모듈
math.sqrt(16) 실행 결과: 4.0

2. random 모듈
random.randint(1, 10) 실행 결과: 1 (1~10 사이의 무작위 정수)

3. datetime 모듈
datetime.datetime.now() 실행 결과: 2026-08-10 10:47:50.671815

4. os 모듈
os.getcwd() 실행 결과: c:\study\python-basic (현재 작업 중인 디렉토리 경로)

5. sys 모듈
sys.version 실행 결과:
3.13.15 (tags/v3.13.15:4061bc4, Aug  5 2026, 13:05:39) [MSC v.1944 64 bit (AMD64)]

6. time 모듈
time.sleep(1) 실행... (1초간 대기합니다)
1초 대기 완료!

In [3]:
import requests

In [4]:
requests.get("https://www.google.com")

In [4]:
import pandas as pd

print("=== 1. DataFrame 생성 ===")
# 사전(dict) 데이터를 기반으로 데이터프레임 생성
data = {
    "이름": ["김철수", "이영희", "박민수", "정지원"],
    "나이": [25, 30, 22, 28],
    "부서": ["개발", "디자인", "개발", "마케팅"],
    "점수": [88, 92, 75, 95]
}
df = pd.DataFrame(data)
print(df)

print("\n=== 2. 기본 정보 및 구조 확인 ===")
print("• 데이터 상단 2행:")
print(df.head(2))

print("\n• 데이터프레임 정보:")
df.info()

print("\n• 수치형 데이터 요약 통계:")
print(df.describe())

print("\n=== 3. 데이터 선택 및 필터링 ===")
# 특정 열 선택
print("• '이름' 열만 선택:")
print(df["이름"])

# 조건 검색 (점수가 85점 이상인 행)
print("\n• 점수가 85점 이상인 사람:")
high_scores = df[df["점수"] >= 85]
print(high_scores)

# loc 사용 (인덱스 및 열 이름 기반 접근)
print("\n• 첫 번째 행의 이름과 점수:")
print(df.loc[0, ["이름", "점수"]])

print("\n=== 4. 데이터 추가 및 수정 ===")
# 새로운 열 추가 (합격 여부)
df["합격여부"] = df["점수"].apply(lambda x: "합격" if x >= 80 else "불합격")

# 열 데이터 수정 (모든 사람의 나이 +1)
df["나이"] = df["나이"] + 1

print(df)

print("\n=== 5. 그룹화 및 통계 (groupby) ===")
# 부서별 평균 점수 구하기
dept_mean = df.groupby("부서")["점수"].mean()
print("• 부서별 평균 점수:")
print(dept_mean)

=== 1. DataFrame 생성 ===
    이름  나이   부서  점수
0  김철수  25   개발  88
1  이영희  30  디자인  92
2  박민수  22   개발  75
3  정지원  28  마케팅  95

=== 2. 기본 정보 및 구조 확인 ===
• 데이터 상단 2행:
    이름  나이   부서  점수
0  김철수  25   개발  88
1  이영희  30  디자인  92

• 데이터프레임 정보:
<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      4 non-null      str
 1   나이      4 non-null      int64
 2   부서      4 non-null      str
 3   점수      4 non-null      int64
dtypes: int64(2), str(2)
memory usage: 260.0 bytes

• 수치형 데이터 요약 통계:
          나이         점수
count   4.00   4.000000
mean   26.25  87.500000
std     3.50   8.812869
min    22.00  75.000000
25%    24.25  84.750000
50%    26.50  90.000000
75%    28.50  92.750000
max    30.00  95.000000

=== 3. 데이터 선택 및 필터링 ===
• '이름' 열만 선택:
0    김철수
1    이영희
2    박민수
3    정지원
Name: 이름, dtype: str

• 점수가 85점 이상인 사람:
    이름  나이   부서  점수
0  김철수  25   개발  88
1  이영희  30  디자인  92
3  정지원  28  마케팅  95

• 첫 번째 행의 이름과 점수:
이름    김철수
점수     88
Name: 0, dtype: object

=== 4. 데이터 추가 및 수정 ===
    이름  나이   부서  점수 합격여부
0  김철수  26   개발  88   합격
1  이영희  31  디자인  92   합격
2  박민수  23   개발  75  불합격
3  정지원  29  마케팅  95   합격

=== 5. 그룹화 및 통계 (groupby) ===
• 부서별 평균 점수:
부서
개발     81.5
디자인    92.0
마케팅    95.0
Name: 점수, dtype: float64

In [8]:
import pandas as pd

data = {
    '이름': ['김철수', '이영희', '박민수', '정수진', '최영호', '한미래', '윤지원'],
    '나이': [25, 28, 22, 31, 27, 24, 29],
    '점수': [85, 92, 78, 95, 88, 73, 91]
}

In [9]:
df=pd.DataFrame(data)
df.head()

    이름  나이  점수
0  김철수  25  85
1  이영희  28  92
2  박민수  22  78
3  정수진  31  95
4  최영호  27  88

In [11]:
df=pd.DataFrame(data)
df

    이름  나이  점수
0  김철수  25  85
1  이영희  28  92
2  박민수  22  78
3  정수진  31  95
4  최영호  27  88
5  한미래  24  73
6  윤지원  29  91

In [18]:
# 1. '나이' 열의 평균 구하기
age_mean = df["나이"].mean()

# 2. 결과 출력
print(f"나이 평균: {round(age_mean, 1)}")

나이 평균: 26.6

In [13]:
round(df["나이"].mean(), 1)

np.float64(26.6)